from os.path import join
import pandas as pd
from snakemake.utils import validate

configfile: 'config/config.yml'
validate(config, "schemas/config.schema.yml")


#needed since std meshes sometimes use L/R instead of lh/rh
#hemi_to_H = dict({'lh': 'L', 'rh': 'R'})
H_to_hemi = dict({'L': 'lh', 'R': 'rh'})

wildcard_constraints:
    surfname='white|pial|sphere.reg',
    volname='T1'


# get subjects from the list of completed freesurfer tar files
subjects, = glob_wildcards(config['in_freesurfer_tar'])


hemis = 'L R'.split()



include: 'rules/common.smk'


rule all_hcp_mmp_to_native:
    input: expand( bids(root='results/hcp_mmp',subject='{subject}',hemi='{hemi}',label='hcpmmp',space='native',suffix='dseg.nii.gz'),subject=subjects,hemi=hemis)
         

include: 'rules/hcp_mmp.smk'
