singularity_freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
#singularity_freesurfer: docker://bids/freesurfer:v6.0.1-5
singularity_connectome_workbench: /project/6007967/software/transparentsingularity/connectome-workbench_1.4.1_20191117.simg/connectome-workbench_1.4.1_20191117.simg
#singularity_connectome_workbench: docker://khanlab/connectome-workbench:latest

#path to your freesurfer license file:
fs_license: /project/6050199/akhanf/opt/freesurfer/.license

#path to subject freesurfer dir (containing surf/ and mri/ subfolders) 
# use the {subject} wildcard here.. 
#in_freesurfer: /scratch/akhanf/camcan_hcp_mmp_to_native/in_freesurfer/sub-{subject}

#optional: specify tar containing a particular subject'a freesurfer folder
in_freesurfer: 'freesurfer/sub-{subject}'
in_freesurfer_root: 'freesurfer'
in_freesurfer_tar: /project/6050199/akhanf/cfmm-bids/data/Burneo/EpLinkPhase3_Baseline/postproc3T_dev/freesurfer_7.1/results/sub-{subject}_freesurfer.tar

#participants_tsv: config/participants.tsv
